stages:
  - build

variables:
  IMG: "rescue"
  ARCH: "amd64"

build_img:
  image: debian:latest
  stage: build
  script:
    - apt update && apt install -y curl xz-utils make sudo git
    - rm -rf /var/cache
    - make NOSVCIMGBUILD=yes ARCH=${ARCH} SVCIMG=${SVCIMG} ${IMG}
  artifacts:
    paths:
      - "*.img"
