stages:
  - build
  - release

variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/mksmolnb/${CI_COMMIT_TAG}"
  IMG: "rescue"
  UPURL: "${PACKAGE_REGISTRY_URL}/${IMG}.img"

build_img:
  image: debian:latest
  stage: build
  script:
    - chmod +x mkimg.sh
    - ./mkimg.sh 
  artifacts:
    paths:
      - *.img

release_img:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${IMG}.img "${UPURL}"



