stages:
  - build
  - release

variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/mksmolnb/${CI_COMMIT_TAG}"
  IMG: "rescue"
  UPURL: "${PACKAGE_REGISTRY_URL}/${IMG}.img"
  DEFARCH: "amd64"
  DEFVERS: "10"
  DEFSETS: "rescue.tar.xz"


build_img:
  image: debian:latest
  stage: build
  script:
    - apt update && apt install -y curl xz-utils
    - rm -rf /var/cache
    - mkdir -p sets/${ARCH}
    - |
      [ -z "${SETS}" ] && SETS=${DEFSETS}
      [ -z "${VERS}" ] && VERS=${DEFVERS}
      [ -z "${ARCH}" ] && ARCH=${DEFARCH}
      DIST="https://nycdn.netbsd.org/pub/NetBSD-daily/netbsd-${VERS}/latest/${ARCH}/binary/sets"
      for set in ${SETS}
      do
        echo "fetching: ${DIST}/${set}"
        curl -L -O --output-dir sets/${ARCH} ${DIST}/${set}
      done
    - chmod +x mkimg.sh
    - ./mkimg.sh 
  artifacts:
    name: "${IMG}"
    paths:
      - ${IMG}.img

release_img:
  stage: release
  image: curlimages/curl:latest
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${IMG}.img "${UPURL}"



