stages:
  - build

variables:
  DEFIMG: "rescue"
  DEFARCH: "amd64"
  DEFVERS: "10"
  DEFSETS: "rescue.tar.xz"
  DEFSIZE: "20"


build_img:
  image: debian:latest
  stage: build
  script:
    - apt update && apt install -y curl xz-utils
    - rm -rf /var/cache
    - |
      : export ${SETS:=${DEFSETS}}
      : export ${VERS:=${DEFVERS}}
      : export ${ARCH:=${DEFARCH}}
      : export ${SIZE:=${DEFSIZE}}
      : export ${IMG:=${DEFIMG}}
      mkdir -p sets
      DIST="https://nycdn.netbsd.org/pub/NetBSD-daily/netbsd-${VERS}/latest/${ARCH}/binary/sets"
      for set in ${SETS}
      do
        curl -L -O --output-dir sets ${DIST}/${set}
      done
    - chmod +x mkimg.sh
    - ./mkimg.sh -x ${SETS} -m ${SIZE} -i ${IMG}.img
  artifacts:
    paths:
      - "*.img"
