stages:
  - build
  - release

variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/mksmolnb/${CI_COMMIT_TAG}"
  IMG: "rescue"
  UPURL: "${PACKAGE_REGISTRY_URL}/${IMG}.img"
  VERS: "10"
  ARCH: "amd64"
  DIST: "https://nycdn.netbsd.org/pub/NetBSD-daily/netbsd-${VERS}/latest/${ARCH}/binary"
  SETS: "etc.tar.xz rescue.tar.xz"


build_img:
  image: debian:latest
  stage: build
  script:
    - apt update && apt install -y curl xz-utils
    - mkdir -p sets/${ARCH}
    - |
      for set in ${SETS}
      do
        curl -L -O --output-dir sets/${ARCH} ${DIST}/${set}
      done
    - ls -l sets/amd64
    - chmod +x mkimg.sh
    - ./mkimg.sh 
  artifacts:
    name: "${IMG}"
    paths:
      - ${IMG}.img

release_img:
  stage: release
  image: curlimages/curl:latest
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${IMG}.img "${UPURL}"



