stages:
  - build

variables:
  IMG: "rescue"

build_img:
  image: debian:latest
  stage: build
  script:
    - apt update && apt install -y curl xz-utils make sudo
    - rm -rf /var/cache
    - make NOSVCIMGBUILD=yes SVCIMG=${SVCIMG} ${IMG}
  artifacts:
    paths:
      - "*.img"
