apiVersion: v1
kind: Pod
metadata:
  name: smolbozo
  namespace: smolbsd
  labels:
    app: smolbozo
spec:
  containers:
  - name: bozohttpd
    image: localhost:5000/smolbozo
    ports:
    - containerPort: 8080
    resources:
      limits:
        squat.ai/kvm: 1

---

apiVersion: v1
kind: Service
metadata:
  name: smolbozo-svc
  namespace: smolbsd
spec:
  selector:
    app: smolbozo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
