name: Build smolBSD image

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      img:
        description: "Image target"
        required: true
        default: "rescue"
      arch:
        description: "Architecture"
        required: true
        default: "amd64"

env:
  IMG: "rescue"
  ARCH: "amd64"

jobs:
  build_img:
    runs-on: ubuntu-latest
    container: debian:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up environment
        run: |
          apt update && apt install -y curl xz-utils make sudo git fuseext2
          touch /in_gh

      - name: Clean cache
        run: rm -rf /var/cache

      - name: Build image
        run: |
          make NOSVCIMGBUILD=yes ARCH=${{ env.ARCH }} SVCIMG=${{ env.SVCIMG }} MOUNTRO=${{ env.MOUNTRO }} ${{ env.IMG }}

      - uses: actions/upload-artifact@v4
        with:
          name: images
          path: "*.img"
